Make schemas editable, use 2 col layout, add CodeMirror
headwirecom/jsonforms-react-spectrum-renderers pull request #72
Opened 2020-12-14 00:15 UTC by uudens

- [x] Make Schema, UISchema, Data textboxes editable
- [x] Add CodeMirror editor to those textboxes
- [x] Move Example selectbox above the textboxes to save space (now it's a 2 column layout)

![editable2](https://user-images.githubusercontent.com/2631515/102028292-1b836100-3db2-11eb-8bf9-4583ab4654f5.gif)

2020-12-14 07:22 UTC, mburri commented
There seems to be something off with the type of `onChange` in the `ExamplesPicker` - at least vs code is telling me this.
But the app compiles and runs fine - not sure what the issue is here...

![image](https://user-images.githubusercontent.com/4577216/102051778-623e7e80-3de5-11eb-85e9-86a3a2b0af86.png)

2020-12-14 07:31 UTC, mburri commented on packages/example/src/ColorSchemeContext.ts
> +  https://github.com/eclipsesource/jsonforms
since this is a new file, the copyright notice does not need to include EclipseSource

2020-12-14 07:31 UTC, mburri commented on packages/example/src/TextArea.tsx
> +  https://github.com/eclipsesource/jsonforms
since this is a new file, the copyright notice does not need to include EclipseSource

2020-12-14 07:35 UTC, mburri requested changes
Thanks for this! That is really nice and I was thinking about something like that before. Two points:
- There's no need to include EclipseSource in the license header for new files
- App.tsx does not seem to be formatted with prettier.

2020-12-14 15:35 UTC, mburri approved these changes

2020-12-14 15:42 UTC, merged

2020-12-17 13:15 UTC, uudens commented
Thank you @mburri for merging!